Making robust for when 'date' does not exist or returns empty
The VERA test VUQCore_unit_test is messing up the path so that the 'date'
command can't even be found.  This was resulting in a CMake failure calling
the function TIMER_PRINT_REL_TIME() with too few arguments.  Now when 'date'
does not return this will just print:

ERROR: Note able to return test times! Is 'date' in your path?

I would be pretty hard to unit test this but I think I need to find a way to
do it.  Now that I have mockprogram.py I think I can unit test this.

Build/Test Cases Summary
Enabled Packages: TriBITS
Enabled all Forward Packages
0) MPI_DEBUG => passed: passed=177,notpassed=0 (0.82 min)
1) SERIAL_RELEASE => Test case SERIAL_RELEASE was not run! => Does not affect push readiness! (-1.00 min)